### ISSUE TITLE
Missing DLL Debug Files

### ISSUE THREAD

**Issue by dlhauser** [conda-forge/pdal-feedstock#104]
Issue:
PDAL would not run because there were missing DLL files. The files were "ucrtbased.dll" and "vcruntime140d.dll". (It's since been worked around.)
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by hobu** [comment]
Thanks for the report. I'll try to track down what is linking Debug runtimes.

**Comment by hobu** [comment]
Can you make a clean environment and check if it is still an issue? I do not see any debug libraries linked in a clean environment on windows with PDAL 2.1.
