### ISSUE TITLE
pdal and proj9 can't live together on python 3.10

### ISSUE THREAD

**Issue by akrherz** [conda-forge/pdal-feedstock#170]
### Comment:

Similar to #154, it appears we have dependency fun again

```
$ mamba create -n dev python=3.10 proj=9.0.0   pdal
Encountered problems while solving:
  - package pdal-2.3.0-hb9c3aac_14 requires libgdal >=3.4.0,<3.5.0a0, but none of the providers can be installed
```

Boggling :)

**Comment by akrherz** [comment]
I think I have isolated the issue to no geotiff=1.7.1 migration done, conda-forge/conda-forge-pinning-feedstock#2654 , but maybe I have yet to find the bottom of the dependency barrel yet

**Comment by hobu** [comment]
> I have isolated the issue to no geotiff=1.7.1 migration done

Can you post an issue in https://github.com/conda-forge/geotiff-feedstock/ ? I don't know how to initiate migrations.

Additionally, PDAL 2.4 is being released today, so all of this stuff will be in flux for a few days.

**Comment by akrherz** [comment]
Hi @hobu , I think my conda-forge-pinning issue was the appropriate place, but am unsure.  Anyway, a new PDAL release will fix this as well as I suspect it will then pickup geotiff=1.7.1 once built, I think.
